services:
  - type: web
    name: 8byte-backend
    env: go
    region: oregon
    plan: free
    envVars:
      - key: GO_VERSION
        value: 1.25.5
    buildCommand: go build -o main .
    startCommand: ./main
